defaultEntryPoints = ["http"]

[web]
address = ":9091"

[entryPoints]
  [entryPoints.http]
  address = ":80"

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "devlocal.zlivio.com"
watch = true
exposedbydefault = false
